# Gerado por `theme set`. Não edite: mexa no manifesto do tema.
#
# O swaylock quer as cores SEM a cerquilha, daí os marcadores de sufixo _raw.

daemonize
ignore-empty-password
show-failed-attempts
indicator-caps-lock
indicator-radius=100
indicator-thickness=8

color=@bg_dark_raw@

inside-color=@bg_dark_raw@
inside-clear-color=@bg_dark_raw@
inside-ver-color=@bg_dark_raw@
inside-wrong-color=@bg_dark_raw@

ring-color=@bg_hl_raw@
ring-clear-color=@yellow_raw@
ring-ver-color=@blue_raw@
ring-wrong-color=@red_raw@

key-hl-color=@magenta_raw@
bs-hl-color=@orange_raw@

line-color=00000000
line-clear-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
separator-color=00000000

text-color=@fg_raw@
text-clear-color=@yellow_raw@
text-ver-color=@blue_raw@
text-wrong-color=@red_raw@

font=Noto Sans
font-size=20
