# Gerado por `theme set`. Não edite: mexa no manifesto do tema.

set $menu wmenu-run -i -f "Noto Sans 11" -N '@bg_dark@' -n '@fg@' -M '@magenta@' -m '@bg_dark@' -S '@blue@' -s '@bg_dark@'

output * bg @bg_dark@ solid_color

# Cores das bordas:      borda      fundo      texto      indicador  borda-filho
client.focused           @blue@     @blue@     @bg_dark@  @magenta@  @blue@
client.focused_inactive  @bg_hl@    @bg_hl@    @fg_dim@   @bg_hl@    @bg_hl@
client.unfocused         @bg@       @bg@       @comment@  @bg@       @bg_hl@
client.urgent            @red@      @red@      @bg_dark@  @red@      @red@
client.background        @bg_dark@
