label="Gruvbox Material"

ghostty_theme="Gruvbox Material Dark"
ghostty_file=""
ghostty_extra="background = #1d2021"

nvim_colorscheme="gruvbox-material"
herdr_theme="gruvbox"
btop_theme="gruvbox_material_dark"

bg_dark=#1d2021
bg=#282828
bg_hl=#3c3836
fg=#d4be98
fg_dim=#a89984
comment=#7c6f64
blue=#7daea3
blue1=#7daea3
cyan=#89b482
magenta=#d3869b
purple=#d3869b
green=#a9b665
yellow=#d8a657
orange=#e78a4e
red=#ea6962
teal=#89b482
